trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Instalar dependências'

  - script: |
      python -m unittest discover -s tests
    displayName: 'Executar testes'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/artifact.zip'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<Nome da Conexão de Serviço>'
      appType: 'webAppLinux'
      appName: '<Nome_do_App>'
      package: '$(Build.ArtifactStagingDirectory)/artifact.zip'
