version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validate_cpf_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
